const device = {
    "DeviceType": {
        "0": "UNKNOWN",
        "1": "PHONE",
        "2": "TABLET",
        "3": "DESKTOP",
        "4": "TV",
        "DESKTOP": 3,
        "PHONE": 1,
        "TABLET": 2,
        "TV": 4,
        "UNKNOWN": 0
    },
    "brand": "google",
    "designName": "emulator64_x86_64_arm64",
    "deviceName": "sdk_gphone64_x86_64",
    "deviceYearClass": 2013,
    "getDeviceTypeAsync": 1,
    "getMaxMemoryAsync": 536870912,
    "getPlatformFeaturesAsync": [
        "android.hardware.sensor.proximity",
        "android.software.adoptable_storage",
        "android.hardware.sensor.accelerometer",
        "android.software.controls",
        "android.hardware.faketouch",
        "android.software.backup",
        "android.hardware.touchscreen",
        "android.hardware.touchscreen.multitouch",
        "android.software.print",
        "android.software.activities_on_secondary_displays",
        "android.software.voice_recognizers",
        "android.software.picture_in_picture",
        "android.hardware.fingerprint",
        "android.hardware.sensor.gyroscope",
        "android.software.vulkan.deqp.level",
        "android.software.cant_save_state",
        "android.hardware.security.model.compatible",
        "android.hardware.sensor.relative_humidity",
        "android.hardware.bluetooth",
        "android.hardware.camera.autofocus",
        "com.google.android.feature.GOOGLE_BUILD",
        "android.hardware.telephony.gsm",
        "android.hardware.telephony.ims",
        "android.software.incremental_delivery",
        "android.software.opengles.deqp.level",
        "android.hardware.camera.concurrent",
        "android.hardware.audio.output",
        "android.software.verified_boot",
        "android.hardware.camera.flash",
        "android.hardware.camera.front",
        "android.hardware.screen.portrait",
        "android.hardware.sensor.ambient_temperature",
        "android.software.home_screen",
        "android.hardware.microphone",
        "android.software.autofill",
        "android.software.securely_removes_users",
        "android.hardware.bluetooth_le",
        "android.hardware.sensor.compass",
        "android.hardware.touchscreen.multitouch.jazzhand",
        "android.hardware.sensor.barometer",
        "android.software.app_widgets",
        "android.software.input_methods",
        "android.hardware.sensor.light",
        "android.hardware.vulkan.version",
        "android.software.companion_device_setup",
        "android.software.device_admin",
        "com.google.android.feature.WELLBEING",
        "android.hardware.wifi.passpoint",
        "android.hardware.camera",
        "android.hardware.screen.landscape",
        "android.hardware.ram.normal",
        "android.hardware.sensor.hinge_angle",
        "android.software.managed_users",
        "android.software.webview",
        "android.hardware.camera.capability.manual_post_processing",
        "android.hardware.camera.any",
        "android.hardware.camera.capability.raw",
        "android.hardware.vulkan.compute",
        "android.software.connectionservice",
        "android.hardware.touchscreen.multitouch.distinct",
        "android.hardware.location.network",
        "android.hardware.camera.ar",
        "android.software.cts",
        "android.hardware.camera.capability.manual_sensor",
        "android.software.app_enumeration",
        "com.google.android.apps.dialer.SUPPORTED",
        "android.hardware.camera.level.full",
        "android.hardware.identity_credential",
        "android.hardware.wifi.direct", 
        "android.software.live_wallpaper",
        "com.google.android.feature.GOOGLE_EXPERIENCE",
        "android.software.ipsec_tunnels",
        "com.google.android.feature.EXCHANGE_6_2",
        "android.hardware.location.gps",
        "android.software.midi",
        "android.hardware.hardware_keystore",
        "android.hardware.wifi",
        "android.hardware.location",
        "android.hardware.vulkan.level",
        "android.software.secure_lock_screen",
        "android.hardware.telephony",
        "android.software.file_based_encryption",
        null
    ],
    "getUptimeAsync": 402949882,
    "hasPlatformFeatureAsync": [Function hasPlatformFeatureAsync],
    "isDevice": true,
    "isRootedExperimentalAsync": [Function isRootedExperimentalAsync],
    "isSideLoadingEnabledAsync": [Function isSideLoadingEnabledAsync],
    "manufacturer": "Google",
    "modelId": null,
    "modelName": "sdk_gphone64_x86_64",
    "osBuildFingerprint": "google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/SE1A.211212.001.B1/8023802:user/release-keys",
    "osBuildId": "SE1A.211212.001.B1",
    "osInternalBuildId": "SE1A.211212.001.B1",
    "osName": "Android",
    "osVersion": "12",
    "platformApiLevel": 31,
    "productName": "emulator64_x86_64_arm64",
    "supportedCpuArchitectures": [
        "x86_64",
        "arm64-v8a"
    ],
    "totalMemory": 2063716352
}